# Generated by Django 2.1 on 2020-04-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='is_tab',
            field=models.BooleanField(default=False, help_text='是否展示', verbose_name='是否展示'),
        ),
    ]
