# Generated by Django 2.1 on 2020-04-09 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20200408_0939'),
        ('goods', '0002_auto_20200409_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(default=0, verbose_name='商品数量')),
                ('signer_mobile', models.CharField(max_length=11, verbose_name='联系电话')),
                ('payment_status', models.IntegerField(choices=[(0, '未付款'), (1, '已付款'), (3, '未评价'), (4, '已评价'), (5, '退款中'), (6, '已退款'), (7, '未退款')], default=0, verbose_name='状态')),
                ('order_sn', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='订单号')),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='交易号')),
                ('post_script', models.CharField(max_length=255, verbose_name='订单留言')),
                ('order_mount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='订单金额')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='订单生成时间')),
                ('buy_time', models.DateTimeField(auto_now_add=True, verbose_name='购买时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Users', verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
    ]
