# Generated by Django 2.1 on 2020-04-07 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='资产')),
            ],
            options={
                'verbose_name_plural': '资产',
                'verbose_name': '资产',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='用户')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('gender', models.IntegerField(choices=[(1, '男'), (0, '女')], default=1, verbose_name='性别')),
                ('mobile', models.CharField(blank=True, max_length=11, verbose_name='手机')),
                # ('email', models.CharField(blank=True, max_length=128, verbose_name='邮箱')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生年月')),
                ('avatar', models.URLField(max_length=255,verbose_name='头像')),
                ('experience', models.IntegerField(default=0, verbose_name='经验')),
                ('grade', models.IntegerField(default=0, verbose_name='等级')),
                ('first_login', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='最后登录时间')),
            ],
            options={
                'verbose_name_plural': '用户',
                'verbose_name': '用户',
            },
        ),
        migrations.AddField(
            model_name='assets',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Users', verbose_name='用户'),
        ),
    ]
