# Generated by Django 2.1 on 2020-04-08 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='users',
            new_name='user',
        ),
    ]
